version: '3.8'

services:
  financehub:
    build: .
    ports:
      - "5000:5000"
    networks:
      - SempreCheioNET
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.financehub.rule=Host(`app.semprecheioapp.com.br`)"
      - "traefik.http.routers.financehub.entrypoints=websecure"
      - "traefik.http.routers.financehub.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.financehub.loadbalancer.server.port=5000"

networks:
  SempreCheioNET:
    external: true